name: date_calendar
version: 0.2.1
description: >
  A calendar interface and Gregorian calendar implementation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/dart_calendar
dev_dependencies:
  test: ^1.3.0
environment:
  sdk: ">=2.12.0 <3.0.0"
